[project]
name = "fly-dspy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dspy>=3.0.4",
    "fastapi>=0.127.1",
    "jinja2>=3.1.0",
    "python-multipart>=0.0.21",
    "uvicorn>=0.40.0",
]
